craftingRecipes:
  bundle: true
  elytra: false
  discs:
    "13": true
    cat: true
    blocks: true
    chirp: true
    far: true
    mall: true
    mellohi: true
    stal: true
    strad: true
    ward: true
    "11": true
    wait: true
    otherside: false
    pigstep: false
  sculkSensor: true
  bell: true