# Default config: ksmpplugin v${project.version} (${minecraft.smpTarget}, MC${minecraft.apiVersion})
# See documentation (all options, possible values, defaults, etc.) on GitHub:
# https://github.com/kiriDevs/ksmpplugin/blob/v${project.version}/docs/recipes.md

recipes:
  crafting:
    chainArmor: chains
    chain:
      cheap: false
      yield: 2
    bundle:
      chest: false
      shell: either
    saddle: true
    cheapLantern: true
    bell: true
    shroomlight: true
  stonecutting:
    wood:
      slabs: true
      stairs: true
