name: Gradle Build
on: [push, pull_request]

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current state of the repo
      uses: actions/checkout@v3

    - name: Setup JDK17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
        java-package: jdk
        architecture: x64
        cache: gradle
      
    - name: Use gradlew to build the project
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kiriSMP_${{ github.sha }}
        path: build/libs/ksmpplugin-*.jar
