name: Gradle Build
on: [push, pull_request]

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current state of the repo
      uses: actions/checkout@v2

    - name: Setup JDK17
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "17"
        java-package: jdk
        architecture: x64
        cache: gradle

    - name: Setup Gradle using gradlew
      run: chmod +x ./gradlew && ./gradlew

    - name: Build project with Gradle
      run: gradle build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kiriSMP_${{ github.sha }}
        path: build/ksmpplugin-*.jar
