name: Maven Build
on: [push, pull_request]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
    - name: Install yamllint
      run: sudo apt update && sudo apt install -y yamllint

    - name: Checkout current state of the repo
      uses: actions/checkout@v4

    - name: Setup JDK17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
        java-package: jdk
        architecture: x64
        cache: maven

    - name: Build project with Maven
      run: mvn verify --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kiriSMP_${{ github.sha }}
        path: target/ksmpplugin-*.jar

    - name: Lint emitted YAML files
      run: 'yamllint -d "{document-start: disable}" target/classes/*.yml'
