name: Maven Build
on: [push, pull_request]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current state of the repo
      uses: actions/checkout@v2

    - name: "Setup JDK17"
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "17"
        java-package: jdk
        architecture: x64
        cache: maven

    - name: Build project with Maven
      run: mvn verify --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kiriSMP_${{ github.sha }}
        path: target/ksmpplugin-*.jar
